use buildsweep_core::{ArtifactKind, SafetyClass};

pub fn classify(name: &str) -> Option<(ArtifactKind, SafetyClass, &'static str)> {
    match name {
        ".dart_tool" => Some((
            ArtifactKind::DartTool,
            SafetyClass::Safe,
            "Dart tooling cache; regenerated by flutter/dart",
        )),
        "build" => Some((
            ArtifactKind::FlutterBuild,
            SafetyClass::Review,
            "Flutter build output; verify before removing",
        )),
        _ => None,
    }
}
